### ISSUE TITLE
Unknown custom element: <font-awesome-icon>

### ISSUE THREAD

**Issue by hchauvat** [FortAwesome/vue-fontawesome#245] opened 2020-08-18 11:16 UTC
**Describe the bug**

I thought I had followed the doc correctly by declaring all the icons I needed directly in main.ts.
But I end up with a Warning from VueJS:
```
console.error
    [Vue warn]: Unknown custom element: <font-awesome-icon> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
    
    found in
    
    ---> <Upload>
           <Root>
```

**Code** 
`main.ts`
```typescript
import { library } from '@fortawesome/fontawesome-svg-core';
import {
    faFilePdf,
    faFileUpload,
    faFileWord,
    faUpload,
} from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
...
library.add(
    faFilePdf,
    faFileUpload,
    faFileWord,
    faUpload,
);
Vue.component('font-awesome-icon', FontAwesomeIcon);
...
new Vue({
    el: '#app',
    ...
    components: { App },
    render(h): VNode {
        return h('App');
    },
});
```

`Upload.vue`
```html
<template>
    <font-awesome-icon :icon="icon"></font-awesome-icon>
</template>

<script lang="ts">
import Vue from 'vue';

export default Vue.extend({
    name: 'upload',
    data() {
        return {
            icon: 'upload',
        },
    },
    methods: {
        setFiletypeIcon(): void {
           ...
        },
    }
</script>
```

**Expected behavior**
Should I move all my icons/library declarations from `main.ts` into any `.vue` file that needs them?

**Versions**
- vue: 2.6.11
- vue-fontawesome: 0.1.9

**Comment by robmadole** [comment] 2020-09-01 19:09
@hchauvat I think the best thing at this point would be for you to create a test case for us. Either a GitHub repo or something like codesandbox.io.

**Comment by jasonlundien** [comment] 2022-11-02 17:17
@hchauvat 

I am going to go ahead and close this issue.  

We have updated our Vue 2 and Vue 3 components and cannot reproduce.  If you feel as if this should remain open just let us know and provide either a GitHub repo or something like codesandbox.io where we could see the issue occuring.

**Closed by jasonlundien** 2022-11-02 17:17 UTC
