### ISSUE TITLE
Can't use scoped classes in FontAwesomeIcon component

### ISSUE THREAD

**Issue by focux** [FortAwesome/vue-fontawesome#173] opened 2019-03-31 19:00 UTC
I don't know if it's the intended behavior, I try to read the docs and I didn't find anything related. I can't use a scoped class in `FontAwesomeIcon` component. I looked into the source (see the image below) and I saw that it's because the parent data attribute is not being added to the component root tag. 

![image](https://user-images.githubusercontent.com/3316818/55293518-54548a00-53c5-11e9-9f2b-dc500e37e911.png)

As a work around I'm using global classes to style the icons. I prefer to have all my styles scoped though.

**Comment by robmadole** [comment] 2019-05-17 16:38
@focux you'll have to provide a reproduction of this using something like codesandbox.io. I'm not 100% sure what the issue is (there is a scoped data attribute on the `svg` element)

**Comment by jasonlundien** [comment] 2022-11-03 20:00
@focux ---

I am going to go ahead and close this issue.  If you are still having troubles and find that this is still a problem just let us know and we can open this back up.

**Closed by jasonlundien** 2022-11-03 20:00 UTC
