### ISSUE TITLE
Typescript error in Nuxt 3 integration

### ISSUE THREAD

**Issue by cmitjans-at-wiris** [FortAwesome/vue-fontawesome#400] opened 2022-09-19 18:16 UTC
**Describe the bug**
Followed [the steps](https://fontawesome.com/docs/web/use-with/vue/use-with#nuxt) on how to integrate FontAwesome with Nuxt 3.

It seems the steps are not correct. I get an error when adding `FontAwesomeIcon` to `vueApp`.
![image](https://user-images.githubusercontent.com/79908984/191085362-2a1ff5c9-d4be-4331-8c6b-ca685fb3efbb.png)

When removing the last parameter (as you would do when integrating FontAwesome [with Vue 3 directly](https://fontawesome.com/docs/web/use-with/vue/add-icons#set-up-the-library) - no Nuxt) the following error shows:

![image](https://user-images.githubusercontent.com/79908984/191085696-7e094019-ed01-4360-bf6b-7ee659a57566.png)

<details>
<summary>View Problem</summary>

```
Argument of type 'ComponentPublicInstance<FontAwesomeIconProps, {}, {}, {}, {}, {}, FontAwesomeIconProps, {}, false, ComponentOptionsBase<any, any, any, any, any, any, any, any, any, {}>>' is not assignable to parameter of type 'Component<any, any, any, ComputedOptions, MethodOptions>'.
  Type 'ComponentPublicInstance<FontAwesomeIconProps, {}, {}, {}, {}, {}, FontAwesomeIconProps, {}, false, ComponentOptionsBase<any, any, any, any, any, any, any, any, any, {}>>' is not assignable to type 'ComponentOptions<any, any, any, ComputedOptions, MethodOptions, any, any, any>'.
    Type 'ComponentPublicInstance<FontAwesomeIconProps, {}, {}, {}, {}, {}, FontAwesomeIconProps, {}, false, ComponentOptionsBase<any, any, any, any, any, any, any, any, any, {}>>' is not assignable to type 'ComponentOptionsBase<any, any, any, ComputedOptions, MethodOptions, any, any, any, string, {}>'.
      Types of property 'computed' are incompatible.
        Type '{ <T>(getter: ComputedGetter<T>, debugOptions?: DebuggerOptions): ComputedRef<T>; <T>(options: WritableComputedOptions<T>, debugOptions?: DebuggerOptions): WritableComputedRef<...>; }' is not assignable to type 'ComputedOptions'.
          Index signature for type 'string' is missing in type '{ <T>(getter: ComputedGetter<T>, debugOptions?: DebuggerOptions): ComputedRef<T>; <T>(options: WritableComputedOptions<T>, debugOptions?: DebuggerOptions): WritableComputedRef<...>; }'.ts(2345)
```
</details>

**Expected behavior**
There should be no typescript errors.

**Additional context**
Dependencies I'm using:
```
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^6.2.0",
    "@fortawesome/free-solid-svg-icons": "^6.2.0",
    "@fortawesome/vue-fontawesome": "^3.0.1"
  }
```

**Comment by robmadole** [comment] 2022-09-20 19:37
Thanks @cmitjans-at-wiris we'll take a look when we can.

**Comment by jonatandorozco** [comment] 2022-10-21 18:14
Any update on this?

**Comment by technatelogy** [comment] 2022-11-04 21:08
This looks like it's happened before and the workaround here worked for me: 
#295

**Comment by tobiasdiez** [comment] 2022-11-21 15:15
This seems to be fixed now (the two args solution at least works for me)

**Comment by jasonlundien** [comment] 2023-03-09 20:25
@cmitjans-at-wiris 

Are you still getting the error using the 3 args ?
```
 nuxtApp.vueApp.component("font-awesome-icon", FontAwesomeIcon, {})
```

I am not seeing the error in the console ?

And if you do not mind sharing... are you using the "Error Lens" to view the inline errors in VS Code or using something else (I am not seeing any inline errors via Error Lens either)?

**Comment by jasonlundien** [comment] 2023-04-17 19:24
@cmitjans-at-wiris ---

Going to go ahead and close this issue.  If you provide a reproducible repo we can re-open.

**Closed as completed by jasonlundien** 2023-04-17 19:24 UTC
Labels: waiting for feedback
