### ISSUE TITLE
Postcss8 loader error on svg core styles.css

### ISSUE THREAD

**Issue by K-zimm** [FortAwesome/vue-fontawesome#341] opened 2022-01-17 18:19 UTC
Running in nuxt with postcss8.

It is having trouble with one particular line. When I commend it out build completes fine and app works great. Seems that it doesn't like the calc() function on line 202 of styles.css in fontawesome-svg-core The parser cries about the -1.

![image](https://user-images.githubusercontent.com/22413842/149820684-42d9de1e-0e5e-483c-b379-5930caf6e045.png)

**Comment by robmadole** [comment] 2022-01-18 15:11
@K-zimm can you provide a reproducible test case for this?

**Comment by tobiasdiez** [comment] 2022-02-13 15:49
I got the same issue while upgrading fontawesome-svg-core from 1.2.36 to 1.3.0 https://github.com/JabRef/JabRefOnline/pull/837. 
As @K-zimm says, the problem is in the line for `left`:
```css
.fa-li {
  left: calc(var(--fa-li-width, 2em) * -1);
  position: absolute;
  text-align: center;
  width: var(--fa-li-width, 2em);
  line-height: inherit; }
```

**Comment by JSAustin** [comment] 2022-02-15 23:20
I also get the same issue. Having a lot of trouble getting past this.

**Comment by robmadole** [comment] 2022-02-22 23:25
That's syntactically correct as far as I know (multiplying by `-1`). Have you reached out to the postcss folks on this?

**Comment by jsayer101** [comment] 2022-03-08 14:14
@K-zimm Hi ! We've got the same error here, how did you solved this issue ? We got no clue how to fix this.

**Comment by tobiasdiez** [comment] 2022-03-21 23:16
I did a bit of digging and it seems like `postcss-values-parser` has/had troubles with the multiplication operator in combination with `-1`, see eg https://github.com/shellscape/postcss-values-parser/issues/126 and https://github.com/shellscape/postcss-values-parser/issues/138. As the latter issue is already closed, one solution might be to upgrade `postcss-values-parser`.

I guess usually `postcss-values-parser` is invoked by `postcss-custom-properties`. More recent version of `postcss-custom-properties` however directly use `postcss-value-parser` (without s) instead of ``postcss-values-parser` (with s). Thus upgrading `postcss-custom-properties` should fix this issue as well. However, some frameworks like nuxt still use a rather old version of these postcss plugins (there is the stalled https://github.com/nuxt/nuxt.js/pull/10060 to upgrade these).

**Comment by tobiasdiez** [comment] 2022-03-22 09:29
That being said, what worked for me was to replace the offending line in `styles.css` with
```
left: calc(-1 * var(--fa-li-width, 2em));
```
(i.e. move the minus 1 multiplication to the front).

**Comment by robmadole** [comment] 2022-03-26 20:15
I'm going to close this as it's not a bug with this library.

**Closed as completed by robmadole** 2022-03-26 20:15 UTC
