### ISSUE TITLE
1x sized icons are messy. Can we disable anti-aliasing?

### ISSUE THREAD

**Issue by ianoble** [FortAwesome/vue-fontawesome#316] opened 2021-06-10 23:32 UTC
**Describe the bug**
The icon looks really messy at the 1x size

**Reproducible test case**
![fontawesome](https://user-images.githubusercontent.com/7987064/121609679-3b19e000-ca09-11eb-9ca0-f7976c547f6a.png)

**Expected behavior**
It seems there should be a way to disable anti-aliasing on icon.

**Desktop (please complete the following information):**
 - Electron app w/Vue
 - Fontawesome 6.0-beta

**Comment by jasonlundien** [comment] 2022-05-20 20:48
@ianoble ---

Are still experiencing issues ?  Can you provide an example repo of the problem if so ?

**Comment by jasonlundien** [comment] 2022-11-03 19:51
I am going to go ahead and close this issue.  I am not able to reproduce and we are now out of Beta and a few releases into V6.  If you feel as if it needs to be reopened just let us know.

**Closed as completed by jasonlundien** 2022-11-03 19:51 UTC
Labels: waiting for feedback
